// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class RustCore {
  Future<String> rustInitCore({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustInitCoreConstMeta;

  Future<bool> rustInitializeVault(
      {required String pin,
      required String hwId,
      required String storagePath,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustInitializeVaultConstMeta;

  Future<SatyaIdentity> rustCreateIdentity(
      {required String label, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustCreateIdentityConstMeta;

  Future<String> rustSignIntent(
      {required String identityId, required String upiUrl, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustSignIntentConstMeta;

  /// PHASE 6.1: Resilient Decentralized Broadcasting
  Future<bool> rustPublishToNostr({required String signedJson, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustPublishToNostrConstMeta;

  Future<List<SatyaIdentity>> rustGetIdentities({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustGetIdentitiesConstMeta;

  Future<String> rustScanQr({required String rawQrString, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustScanQrConstMeta;
}

class SatyaIdentity {
  /// Unique internal UUID generated by Rust
  final String id;

  /// User-friendly label for identification
  final String label;

  /// The actual Decentralized Identifier string
  final String did;

  const SatyaIdentity({
    required this.id,
    required this.label,
    required this.did,
  });
}

class RustCoreImpl implements RustCore {
  final RustCorePlatform _platform;
  factory RustCoreImpl(ExternalLibrary dylib) =>
      RustCoreImpl.raw(RustCorePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory RustCoreImpl.wasm(FutureOr<WasmModule> module) =>
      RustCoreImpl(module as ExternalLibrary);
  RustCoreImpl.raw(this._platform);
  Future<String> rustInitCore({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_rust_init_core(port_),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kRustInitCoreConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustInitCoreConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_init_core",
        argNames: [],
      );

  Future<bool> rustInitializeVault(
      {required String pin,
      required String hwId,
      required String storagePath,
      dynamic hint}) {
    var arg0 = _platform.api2wire_String(pin);
    var arg1 = _platform.api2wire_String(hwId);
    var arg2 = _platform.api2wire_String(storagePath);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_rust_initialize_vault(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_bool,
      parseErrorData: _wire2api_FrbAnyhowException,
      constMeta: kRustInitializeVaultConstMeta,
      argValues: [pin, hwId, storagePath],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustInitializeVaultConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_initialize_vault",
        argNames: ["pin", "hwId", "storagePath"],
      );

  Future<SatyaIdentity> rustCreateIdentity(
      {required String label, dynamic hint}) {
    var arg0 = _platform.api2wire_String(label);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_rust_create_identity(port_, arg0),
      parseSuccessData: _wire2api_satya_identity,
      parseErrorData: _wire2api_FrbAnyhowException,
      constMeta: kRustCreateIdentityConstMeta,
      argValues: [label],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustCreateIdentityConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_create_identity",
        argNames: ["label"],
      );

  Future<String> rustSignIntent(
      {required String identityId, required String upiUrl, dynamic hint}) {
    var arg0 = _platform.api2wire_String(identityId);
    var arg1 = _platform.api2wire_String(upiUrl);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_rust_sign_intent(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      parseErrorData: _wire2api_FrbAnyhowException,
      constMeta: kRustSignIntentConstMeta,
      argValues: [identityId, upiUrl],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustSignIntentConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_sign_intent",
        argNames: ["identityId", "upiUrl"],
      );

  Future<bool> rustPublishToNostr({required String signedJson, dynamic hint}) {
    var arg0 = _platform.api2wire_String(signedJson);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_rust_publish_to_nostr(port_, arg0),
      parseSuccessData: _wire2api_bool,
      parseErrorData: _wire2api_FrbAnyhowException,
      constMeta: kRustPublishToNostrConstMeta,
      argValues: [signedJson],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustPublishToNostrConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_publish_to_nostr",
        argNames: ["signedJson"],
      );

  Future<List<SatyaIdentity>> rustGetIdentities({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_rust_get_identities(port_),
      parseSuccessData: _wire2api_list_satya_identity,
      parseErrorData: _wire2api_FrbAnyhowException,
      constMeta: kRustGetIdentitiesConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustGetIdentitiesConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_get_identities",
        argNames: [],
      );

  Future<String> rustScanQr({required String rawQrString, dynamic hint}) {
    var arg0 = _platform.api2wire_String(rawQrString);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_rust_scan_qr(port_, arg0),
      parseSuccessData: _wire2api_String,
      parseErrorData: _wire2api_FrbAnyhowException,
      constMeta: kRustScanQrConstMeta,
      argValues: [rawQrString],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRustScanQrConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "rust_scan_qr",
        argNames: ["rawQrString"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  FrbAnyhowException _wire2api_FrbAnyhowException(dynamic raw) {
    return FrbAnyhowException(raw as String);
  }

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  List<SatyaIdentity> _wire2api_list_satya_identity(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_satya_identity).toList();
  }

  SatyaIdentity _wire2api_satya_identity(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SatyaIdentity(
      id: _wire2api_String(arr[0]),
      label: _wire2api_String(arr[1]),
      did: _wire2api_String(arr[2]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class RustCorePlatform extends FlutterRustBridgeBase<RustCoreWire> {
  RustCorePlatform(ffi.DynamicLibrary dylib) : super(RustCoreWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustCoreWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustCoreWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustCoreWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(int ptr) {
    return _get_dart_object(ptr);
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
    'get_dart_object',
  );
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(int ptr) {
    return _drop_dart_object(ptr);
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
    'drop_dart_object',
  );
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(Object handle) {
    return _new_dart_opaque(handle);
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
    'new_dart_opaque',
  );
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(ffi.Pointer<ffi.Void> obj) {
    return _init_frb_dart_api_dl(obj);
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
    'init_frb_dart_api_dl',
  );
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_rust_init_core(int port_) {
    return _wire_rust_init_core(port_);
  }

  late final _wire_rust_init_corePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'wire_rust_init_core',
  );
  late final _wire_rust_init_core =
      _wire_rust_init_corePtr.asFunction<void Function(int)>();

  void wire_rust_initialize_vault(
    int port_,
    ffi.Pointer<wire_uint_8_list> pin,
    ffi.Pointer<wire_uint_8_list> hw_id,
    ffi.Pointer<wire_uint_8_list> storage_path,
  ) {
    return _wire_rust_initialize_vault(port_, pin, hw_id, storage_path);
  }

  late final _wire_rust_initialize_vaultPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
          )>>('wire_rust_initialize_vault');
  late final _wire_rust_initialize_vault =
      _wire_rust_initialize_vaultPtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
          )>();

  void wire_rust_create_identity(
    int port_,
    ffi.Pointer<wire_uint_8_list> label,
  ) {
    return _wire_rust_create_identity(port_, label);
  }

  late final _wire_rust_create_identityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_rust_create_identity');
  late final _wire_rust_create_identity = _wire_rust_create_identityPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_rust_sign_intent(
    int port_,
    ffi.Pointer<wire_uint_8_list> identity_id,
    ffi.Pointer<wire_uint_8_list> upi_url,
  ) {
    return _wire_rust_sign_intent(port_, identity_id, upi_url);
  }

  late final _wire_rust_sign_intentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
          )>>('wire_rust_sign_intent');
  late final _wire_rust_sign_intent = _wire_rust_sign_intentPtr.asFunction<
      void Function(
        int,
        ffi.Pointer<wire_uint_8_list>,
        ffi.Pointer<wire_uint_8_list>,
      )>();

  void wire_rust_publish_to_nostr(
    int port_,
    ffi.Pointer<wire_uint_8_list> signed_json,
  ) {
    return _wire_rust_publish_to_nostr(port_, signed_json);
  }

  late final _wire_rust_publish_to_nostrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_rust_publish_to_nostr');
  late final _wire_rust_publish_to_nostr = _wire_rust_publish_to_nostrPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_rust_get_identities(int port_) {
    return _wire_rust_get_identities(port_);
  }

  late final _wire_rust_get_identitiesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'wire_rust_get_identities',
  );
  late final _wire_rust_get_identities =
      _wire_rust_get_identitiesPtr.asFunction<void Function(int)>();

  void wire_rust_scan_qr(
    int port_,
    ffi.Pointer<wire_uint_8_list> raw_qr_string,
  ) {
    return _wire_rust_scan_qr(port_, raw_qr_string);
  }

  late final _wire_rust_scan_qrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_rust_scan_qr');
  late final _wire_rust_scan_qr = _wire_rust_scan_qrPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(int len) {
    return _new_uint_8_list_0(len);
  }

  late final _new_uint_8_list_0Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>(
      'new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(WireSyncReturn ptr) {
    return _free_WireSyncReturn(ptr);
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
    'free_WireSyncReturn',
  );
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
