// Adding Persistence and Security

/// PRINCIPAL DESIGN: Domain Model Synchronization
/// This class MUST mirror the Rust struct in 'rust_core/src/domain.rs' 
/// to ensure seamless FFI serialization and consistency.
class SatyaIdentity {
  /// Unique internal UUID generated by Rust for local lookups.
  final String id;
  
  /// User-friendly label (e.g., "Milk Business", "Personal Wallet").
  final String label;
  
  /// The actual Decentralized Identifier string (did:satya:...).
  final String did;

  SatyaIdentity({
    required this.id,
    required this.label,
    required this.did,
  });

  /// Factory for JSON transformation used by the FFI Bridge.
  factory SatyaIdentity.fromJson(Map<String, dynamic> json) {
    return SatyaIdentity(
      id: json['id'] as String,
      label: json['label'] as String,
      did: json['did'] as String,
    );
  }

  /// Converts the domain object back to JSON for storage or transmission.
  Map<String, dynamic> toJson() => {
    'id': id,
    'label': label,
    'did': did,
  };
}