/**
 * PROJECT SATYA: SECURE IDENTITY BRIDGE
 * =====================================
 * PHASE: 4.0 (Identity Lifecycle & Persistence)
 * VERSION: 1.1.0
 * STATUS: STABLE
 * DESCRIPTION:
 * Defines the core domain models for Project Satya. Ensures the Dart layer 
 * perfectly mirrors the Rust structs to facilitate FFI serialization.
 * CHANGE LOG:
 * - Phase 1.0: Basic identity skeleton.
 * - Phase 3.0: Added label and ID fields for persistence.
 * - Phase 4.0: Standardized Phase headers.
 */

class SatyaIdentity {
  /// Unique internal UUID generated by Rust for local lookups.
  final String id;
  
  /// User-friendly label (e.g., "Milk Business", "Personal Wallet").
  final String label;
  
  /// The actual Decentralized Identifier string (did:satya:...).
  final String did;

  SatyaIdentity({
    required this.id,
    required this.label,
    required this.did,
  });

  factory SatyaIdentity.fromJson(Map<String, dynamic> json) {
    return SatyaIdentity(
      id: json['id'] as String,
      label: json['label'] as String,
      did: json['did'] as String,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'label': label,
    'did': did,
  };
}

class UpiIntent {
  final String vpa;
  final String name;
  final String amount;
  final String currency;

  UpiIntent({
    required this.vpa,
    required this.name,
    required this.amount,
    required this.currency,
  });

  factory UpiIntent.fromJson(Map<String, dynamic> json) {
    return UpiIntent(
      vpa: json['vpa'] as String,
      name: json['name'] as String,
      amount: json['amount'] as String,
      currency: json['currency'] as String,
    );
  }
}