#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

use crate::domain::SatyaIdentity;

// Section: wire functions

fn wire_rust_init_core_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "rust_init_core",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Result::<_, ()>::Ok(rust_init_core()),
    )
}
fn wire_rust_reset_vault_impl(
    port_: MessagePort,
    storage_path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "rust_reset_vault",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_storage_path = storage_path.wire2api();
            move |task_callback| rust_reset_vault(api_storage_path)
        },
    )
}
fn wire_rust_initialize_vault_impl(
    port_: MessagePort,
    pin: impl Wire2Api<String> + UnwindSafe,
    hw_id: impl Wire2Api<String> + UnwindSafe,
    storage_path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "rust_initialize_vault",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_pin = pin.wire2api();
            let api_hw_id = hw_id.wire2api();
            let api_storage_path = storage_path.wire2api();
            move |task_callback| rust_initialize_vault(api_pin, api_hw_id, api_storage_path)
        },
    )
}
fn wire_rust_create_identity_impl(port_: MessagePort, label: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, SatyaIdentity, _>(
        WrapInfo {
            debug_name: "rust_create_identity",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_label = label.wire2api();
            move |task_callback| rust_create_identity(api_label)
        },
    )
}
fn wire_rust_sign_intent_impl(
    port_: MessagePort,
    identity_id: impl Wire2Api<String> + UnwindSafe,
    upi_url: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "rust_sign_intent",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_identity_id = identity_id.wire2api();
            let api_upi_url = upi_url.wire2api();
            move |task_callback| rust_sign_intent(api_identity_id, api_upi_url)
        },
    )
}
fn wire_rust_publish_to_nostr_impl(
    port_: MessagePort,
    signed_json: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "rust_publish_to_nostr",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_signed_json = signed_json.wire2api();
            move |task_callback| rust_publish_to_nostr(api_signed_json)
        },
    )
}
fn wire_rust_get_identities_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Vec<SatyaIdentity>, _>(
        WrapInfo {
            debug_name: "rust_get_identities",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| rust_get_identities(),
    )
}
fn wire_rust_scan_qr_impl(port_: MessagePort, raw_qr_string: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "rust_scan_qr",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_raw_qr_string = raw_qr_string.wire2api();
            move |task_callback| rust_scan_qr(api_raw_qr_string)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for SatyaIdentity {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.did.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for SatyaIdentity {}
impl rust2dart::IntoIntoDart<SatyaIdentity> for SatyaIdentity {
    fn into_into_dart(self) -> Self {
        self
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use self::io::*;
